### ISSUE TITLE
Whites are orange

### ISSUE THREAD

**Issue by Bboy486** [awawa-dev/HyperHDR#19] opened 2020-12-23 22:57 UTC
## Bug report, debug log and your config file (optional but could be very helpful)

2020-12-22T04:54:45.691Z [hyperiond EFFECTFILES] (INFO) 39 effects loaded from directory :/effects/
 2020-12-22T04:54:45.697Z [hyperiond EFFECTFILES] (INFO) 22 effect schemas loaded from directory :/effects/schema/
 2020-12-22T04:54:45.699Z [hyperiond EFFECTFILES] (INFO) 0 effects loaded from directory /.hyperion/custom-effects
 2020-12-22T04:54:48.264Z [hyperiond DAEMON] (INFO) No platform capture supported on this platform
 2020-12-22T04:54:48.514Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) Signal threshold set to: {12, 12, 12} and frames: 200
 2020-12-22T04:54:48.515Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) CEC detection is now disabled
 2020-12-22T04:54:48.516Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) Signal detection area set to: 0.250000,0.250000 x 0.750000,0.750000
 2020-12-22T04:54:48.518Z [hyperiond JSONSERVER] (INFO) Started on port 19444
 2020-12-22T04:54:46.991Z [hyperiond LEDDEVICE] (INFO) Start LedDevice 'ws281x'.
 2020-12-22T04:54:47.012Z [hyperiond FLATBUFCONN] (INFO) Connecting to Hyperion: 127.0.0.1:19401
 2020-12-22T04:54:48.355Z [hyperiond LEDDEVICE] (INFO) Start LedDevice 'philipshue'.
 2020-12-22T04:54:48.357Z [hyperiond EFFECTENGINE] (INFO) Run effect "Rainbow swirl fast" on channel 0
 2020-12-22T04:54:48.542Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) Multithreading for V4L2 is enabled. Available thread's count 4
 2020-12-22T04:54:48.545Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) configured v4l device: /dev/video15
 2020-12-22T04:54:52.509Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) Started
 2020-12-22T04:54:52.510Z [hyperiond HYPERION] (INFO) Hyperion instance 'Wled Den instance' has been started
 2020-12-22T04:54:48.473Z [hyperiond HYPERION] (INFO) Initial foreground effect 'Rainbow swirl fast' started
 2020-12-22T04:54:52.510Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) Multithreading for V4L2 is enabled. Available thread's count 4
 2020-12-22T04:54:52.511Z [hyperiond HYPERION] (INFO) Hyperion instance 'Hue Den Instance' has been started
 2020-12-22T04:54:48.509Z [hyperiond LEDDEVICE] (INFO) Light ID 16 ("Den - Hue Play Left", LED index "0") created
 2020-12-22T04:54:48.510Z [hyperiond LEDDEVICE] (INFO) Light ID 17 ("Den - Hue Play Right", LED index "1") created
 2020-12-22T04:54:48.533Z [hyperiond FLATBUFSERVER] (INFO) Started on port 19400
 2020-12-22T04:54:48.539Z [hyperiond PROTOSERVER] (INFO) Started on port 19445
 2020-12-22T04:54:48.641Z [hyperiond WEBSERVER] (INFO) Started on port 8090 name 'Hyperion Webserver'
 2020-12-22T04:54:49.086Z [hyperiond LEDDEVICE] (ERROR) Device disabled, device 'philipshue' signals error: '(2) body contains invalid json, Resource:/lights/16/state'
 2020-12-22T04:54:49.165Z [hyperiond LEDDEVICE] (ERROR) Device disabled, device 'philipshue' signals error: '(2) body contains invalid json, Resource:/lights/17/state'
 2020-12-22T04:54:53.208Z [hyperiond WEBSERVER] (INFO) Started on port 8092 name 'Hyperion Webserver'
 2020-12-22T04:56:53.594Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) Signal detection area set to: 0.250000,0.250000 x 0.750000,0.750000
 2020-12-22T04:56:53.595Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) Signal threshold set to: {12, 12, 12} and frames: 200
 2020-12-22T04:56:53.598Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) Stopped
 2020-12-22T04:56:53.598Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) Multithreading for V4L2 is enabled. Available thread's count 4
 2020-12-22T04:56:53.854Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) configured v4l device: /dev/video0
 2020-12-22T04:56:53.914Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) Started
 2020-12-22T04:56:53.924Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) Stopped
 2020-12-22T04:56:53.925Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) Multithreading for V4L2 is enabled. Available thread's count 4
 2020-12-22T04:56:53.927Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) configured v4l device: /dev/video0
 2020-12-22T04:56:53.976Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) Started
 2020-12-22T04:56:54.315Z [hyperiond LEDDEVICE] (ERROR) Device disabled, device 'philipshue' signals error: '(2) body contains invalid json, Resource:/lights/16/state'
 2020-12-22T04:56:54.352Z [hyperiond LEDDEVICE] (ERROR) Device disabled, device 'philipshue' signals error: '(201) parameter, xy, is not modifiable. Device is set to off., Resource:/lights/16/state/xy'
 2020-12-22T04:56:54.385Z [hyperiond LEDDEVICE] (ERROR) Device disabled, device 'philipshue' signals error: '(2) body contains invalid json, Resource:/lights/17/state'
 2020-12-22T13:19:14.649Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) Multithreading for V4L2 is enabled. Available thread's count 4
 2020-12-22T13:19:43.079Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) Previous line repeats 1 times
 2020-12-22T13:19:43.079Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) Stopped
 2020-12-22T13:19:43.079Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) Multithreading for V4L2 is enabled. Available thread's count 4
 2020-12-22T13:19:43.081Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) configured v4l device: /dev/video0
 2020-12-22T13:19:43.117Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) Started
 2020-12-22T13:19:43.118Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) Signal detection is now disabled
 2020-12-22T13:19:43.118Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) Signal detection area set to: 0.250000,0.250000 x 0.750000,0.750000
 2020-12-22T13:19:43.118Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) Signal threshold set to: {12, 12, 12} and frames: 200
 2020-12-22T13:19:43.122Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) Stopped
 2020-12-22T13:19:43.123Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) Multithreading for V4L2 is enabled. Available thread's count 4
 2020-12-22T13:19:43.124Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) configured v4l device: /dev/video0
 2020-12-22T13:19:43.166Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) Started
 2020-12-22T13:19:43.171Z [hyperiond V4L2:/DEV/VIDEO15] (ERROR) Frame index = 901898, inactive or critical VIDIOC_QBUF error in v4l2 driver. Buf index = 1, worker = 0, is_active = 1.
 2020-12-23T01:43:27.300Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) Signal detection is now enabled
 2020-12-23T01:43:27.302Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) Signal detection area set to: 0.250000,0.250000 x 0.750000,0.750000
 2020-12-23T01:43:27.302Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) Signal threshold set to: {12, 12, 12} and frames: 200
 2020-12-23T01:43:27.310Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) Stopped
 2020-12-23T01:43:27.310Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) Multithreading for V4L2 is enabled. Available thread's count 4
 2020-12-23T01:43:27.313Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) configured v4l device: /dev/video0
 2020-12-23T01:43:27.490Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) Started
 2020-12-23T01:43:47.897Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) Signal detection is now disabled
 2020-12-23T01:43:47.897Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) Signal detection area set to: 0.250000,0.250000 x 0.750000,0.750000
 2020-12-23T01:43:47.897Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) Signal threshold set to: {12, 12, 12} and frames: 200
 2020-12-23T01:43:47.929Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) Stopped
 2020-12-23T01:43:47.930Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) Multithreading for V4L2 is enabled. Available thread's count 4
 2020-12-23T01:43:47.931Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) configured v4l device: /dev/video0
 2020-12-23T01:43:48.069Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) Started
 2020-12-23T01:43:48.069Z [hyperiond V4L2:/DEV/VIDEO15] (ERROR) Frame index = 2241654, inactive or critical VIDIOC_QBUF error in v4l2 driver. Buf index = 1, worker = 1, is_active = 1.
 2020-12-23T01:44:05.180Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) Signal detection is now enabled
 2020-12-23T01:44:05.181Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) Signal detection area set to: 0.250000,0.250000 x 0.750000,0.750000
 2020-12-23T01:44:05.181Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) Signal threshold set to: {12, 12, 12} and frames: 200
 2020-12-23T01:44:05.187Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) Stopped
 2020-12-23T01:44:05.187Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) Multithreading for V4L2 is enabled. Available thread's count 4
 2020-12-23T01:44:05.189Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) configured v4l device: /dev/video0
 2020-12-23T01:44:05.231Z [hyperiond V4L2:/DEV/VIDEO15] (INFO) Started
 2020-12-23T01:44:05.255Z [hyperiond V4L2:/DEV/VIDEO15] (ERROR) Frame index = 2242164, inactive or critical VIDIOC_QBUF error in v4l2 driver. Buf index = 1, worker = 0, is_active = 1.
 2020-12-23T22:56:37.828Z [hyperiond WEBSOCKET] (DEBUG) (WebSocketClient.cpp:204:sendClose()) send close: 1000 
 2020-12-23T22:56:38.459Z [hyperiond WEBSOCKET] (DEBUG) (WebSocketClient.cpp:30:WebSocketClient()) New connection from ::ffff:192.168.1.33
 2020-12-23T22:56:38.461Z [hyperiond WEBSOCKET] (DEBUG) (JsonAPI.cpp:85:handleInstanceSwitch()) Client '::ffff:192.168.1.33' switch to Hyperion instance 0
 2020-12-23T22:56:39.633Z [hyperiond HYPERION] (DEBUG) (PriorityMuxer.cpp:251:setInputImage()) Priority 230 is now inactive
 2020-12-23T22:56:39.634Z [hyperiond HYPERION] (DEBUG) (PriorityMuxer.cpp:351:setCurrentTime()) Set visible priority to 255
 2020-12-23T22:56:40.265Z [hyperiond HYPERION] (DEBUG) (PriorityMuxer.cpp:251:setInputImage()) Priority 230 is now active
 2020-12-23T22:56:40.265Z [hyperiond HYPERION] (DEBUG) (PriorityMuxer.cpp:351:setCurrentTime()) Set visible priority to 230
 2020-12-23T22:56:40.546Z [hyperiond WEBSOCKET] (DEBUG) (JsonAPI.cpp:1087:handleLoggingCommand()) log streaming activated for client ::ffff:192.168.1.33

#### Steps to reproduce
Have a video with a white backgroud

#### What is expected?
Lights should be white

#### What is actually happening?
![IMG_20201223_155253.jpg](https://user-images.githubusercontent.com/16495657/103042538-359e0b80-4537-11eb-954b-e6bcd130fc6b.jpg)

#### System

Hyperion Server: - Build: (HEAD detached at 877073f) (GitHub-d058b91/877073f-1606860086) - Build time: Dec 1 2020 23:05:27 - Git Remote: https://github.com/awawa-dev/HyperHDR - Version: 12.1.0.0 - UI Lang: auto (BrowserLang: en-US) - UI Access: default - Avail Capt: v4l2 - Database: read/write Hyperion Server OS: - Distribution: HyperBian GNU/Linux 10 (buster) - Architecture: arm - CPU Model: ARMv7 Processor rev 3 (v7l) - CPU Type: Raspberry Pi 4 Model B Rev 1.2 - CPU Revision: c03112 - CPU Hardware: BCM2711 - Kernel: linux (5.4.72-v7l+ (WS: 32)) - Qt Version: 5.11.3 - Python Version: 3.7.3 - Browser: Mozilla/5.0 (

**Comment by awawa-dev** [comment] 2020-12-23 23:18
1) check what you have on the preview in the WWW
2) calibration tab maybe come in handy?

**Comment by awawa-dev** [comment] 2020-12-23 23:32
BTW this log is from old version. Please use v14 as it contains serious fixes for Philips. Though I can't guarantee it will work all the time for a few days and in this case from the logs (the hue instance simply powered off and has nothing to do with the white on the TV screen).

**Comment by Bboy486** [comment] 2020-12-23 23:42
I am not using those hue bars really as I couldn't get my wled and play bars instances to work at the same time.

**Comment by Bboy486** [comment] 2020-12-23 23:44
What's the www?
I ran the rgb byte order and calibrated. This only happens on a pure white image. 

![IMG_20201223_164428.jpg](https://user-images.githubusercontent.com/16495657/103044544-23739b80-453e-11eb-993c-4f1db7605e98.jpg)

**Comment by awawa-dev** [comment] 2020-12-23 23:48
1) I explained to you that the Philips Hue is not working according to these cut off logs
2) It stack on some old/orange color when it was powered off
3) please use v14 and provide full log next time

**Comment by Bboy486** [comment] 2020-12-23 23:51
Do I just run a new ever to the new version or can I apt-get update?

**Comment by awawa-dev** [comment] 2020-12-23 23:59
You must do the apt-get remove (old version) and apt-get install (new version) from the command line.

**Comment by Bboy486** [comment] 2020-12-24 02:07
HyperHDR Server: 
- Build:           (HEAD detached at d35314e) (GitHub-9795cc8/d35314e-1608750238)
- Build time:      Dec 23 2020 20:19:43
- Git Remote:      https://github.com/awawa-dev/HyperHDR
- Version:         14.0.0.0
- UI Lang:         auto (BrowserLang: en-US)
- UI Access:       default
- Avail Capt:      v4l2
- Database:        read/write

HyperHDR Server OS: 
- Distribution:   Raspbian GNU/Linux 10 (buster)
- Architecture:   arm
- CPU Model:      ARMv7 Processor rev 3 (v7l)
- CPU Type:       Raspberry Pi 4 Model B Rev 1.2
- CPU Revision:   c03112
- CPU Hardware:   BCM2711
- Kernel:         linux (5.4.79-v7l+ (WS: 32))
- Qt Version:     5.11.3
- Python Version: 3.7.3
- Browser:        Mozilla/5.0 (Linux; Android 10; SM-N975U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.101 Mobile Safari/537.36 
3rd party licenses	
===========

2020-12-24T02:04:58.686Z [hyperiond EFFECTFILES] (INFO) 39 effects loaded from directory :/effects/
 2020-12-24T02:04:58.692Z [hyperiond EFFECTFILES] (INFO) 22 effect schemas loaded from directory :/effects/schema/
 2020-12-24T02:04:58.695Z [hyperiond EFFECTFILES] (INFO) 0 effects loaded from directory /.hyperion/custom-effects
 2020-12-24T02:04:58.739Z [hyperiond SETTINGSMGR] (DEBUG) (SettingsManager.cpp:109:SettingsManager()) Settings database initialized
 2020-12-24T02:04:58.742Z [hyperiond BLACKBORDER] (DEBUG) (BlackBorderProcessor.cpp:64:handleSettingsUpdate()) Set mode to: default
 2020-12-24T02:04:58.742Z [hyperiond COMPONENTREG] (DEBUG) (ComponentRegister.cpp:36:setNewComponentState()) Blackborder detector: enabled
 2020-12-24T02:04:58.743Z [hyperiond RgbTransform] (DEBUG) (RgbTransform.cpp:35:init()) RGB transform classic_config: 0, saturationGain: 1.000000, luminanceGain: 1.000000
 2020-12-24T02:04:58.743Z [hyperiond RgbTransform] (DEBUG) (RgbTransform.cpp:35:init()) RGB transform classic_config: 1, saturationGain: 1.000000, luminanceGain: 1.000000
 2020-12-24T02:04:58.751Z [hyperiond ChannelAdjust_RED] (DEBUG) (RgbChannelAdjustment.cpp:37:setCorrection()) set color correction to 255
 2020-12-24T02:04:58.751Z [hyperiond ChannelAdjust_BLUE] (DEBUG) (RgbChannelAdjustment.cpp:37:setCorrection()) set color correction to 255
 2020-12-24T02:04:58.751Z [hyperiond ChannelAdjust_GREEN] (DEBUG) (RgbChannelAdjustment.cpp:37:setCorrection()) set color correction to 255
 2020-12-24T02:05:02.878Z [hyperiond DAEMON] (INFO) No platform capture supported on this platform
 2020-12-24T02:05:03.119Z [hyperiond V4L2:/DEV/VIDEO0] (DEBUG) (Grabber.cpp:79:setWidthHeight()) Set new width: 1280, height: 720 for capture
 2020-12-24T02:05:03.119Z [hyperiond V4L2:/DEV/VIDEO0] (DEBUG) (V4L2Grabber.cpp:1409:setDeviceVideoStandard()) setDeviceVideoStandard restarting v4l2 grabber. Old: '' new: '/dev/video0'
 2020-12-24T02:05:03.119Z [hyperiond V4L2:/DEV/VIDEO0] (DEBUG) (V4L2Grabber.cpp:86:V4L2Grabber()) Init pixel format: 6
 2020-12-24T02:05:03.120Z [hyperiond V4L2:/DEV/VIDEO0] (DEBUG) (V4L2Grabber.cpp:196:setHdrToneMappingEnabled()) setHdrToneMappingMode to: Disabled
 2020-12-24T02:05:03.120Z [hyperiond V4L2:/DEV/VIDEO0] (DEBUG) (V4L2Grabber.cpp:182:setFpsSoftwareDecimation()) setFpsSoftwareDecimation to: 1
 2020-12-24T02:05:03.121Z [hyperiond V4L2:/DEV/VIDEO0] (DEBUG) (V4L2Grabber.cpp:1516:setEncoding()) Force encoding (setEncoding): NO_CHANGE (NO_CHANGE)
 2020-12-24T02:05:03.121Z [hyperiond V4L2:/DEV/VIDEO0] (INFO) Signal threshold set to: {12, 12, 12} and frames: 200
 2020-12-24T02:05:03.122Z [hyperiond V4L2:/DEV/VIDEO0] (INFO) CEC detection is now disabled
 2020-12-24T02:05:03.122Z [hyperiond V4L2:/DEV/VIDEO0] (DEBUG) (V4L2Grabber.cpp:1551:setBrightnessContrastSaturationHue()) setBrightnessContrastSaturationHue nothing changed
 2020-12-24T02:05:03.122Z [hyperiond V4L2:/DEV/VIDEO0] (INFO) Signal detection area set to: 0.250000,0.250000 x 0.750000,0.750000
 2020-12-24T02:05:03.123Z [hyperiond DAEMON] (DEBUG) (hyperiond.cpp:453:handleSettingsUpdate()) V4L2 grabber created
 2020-12-24T02:05:03.124Z [hyperiond JSONSERVER] (DEBUG) (JsonServer.cpp:28:JsonServer()) Created instance
 2020-12-24T02:05:03.125Z [hyperiond JSONSERVER] (INFO) Started on port 19444
 2020-12-24T02:05:02.890Z [hyperiond LEDDEVICE] (INFO) Start LedDevice 'ws281x'.
 2020-12-24T02:05:02.890Z [hyperiond COMPONENTREG] (DEBUG) (ComponentRegister.cpp:36:setNewComponentState()) Smoothing: enabled
 2020-12-24T02:05:02.891Z [hyperiond LEDDEVICE] (DEBUG) (LedDevice.cpp:149:init()) deviceConfig: [{"colorOrder":"grb","currentLedCount":268,"dma":5,"gpio":18,"hardwareLedCount":4,"invert":false,"latchTime":0,"leds":277,"pwmchannel":0,"rewriteTime":1000,"rgbw":false,"type":"ws281x","whiteAlgorithm":"subtract_minimum"}]
 2020-12-24T02:05:02.891Z [hyperiond LEDDEVICE] (DEBUG) (LedDevice.cpp:408:setLatchTime()) LatchTime updated to 0ms
 2020-12-24T02:05:02.891Z [hyperiond LEDDEVICE] (DEBUG) (LedDevice.cpp:429:setRewriteTime()) Refresh interval = 1000ms
 2020-12-24T02:05:02.892Z [hyperiond LEDDEVICE] (DEBUG) (LedDevice.cpp:435:setRewriteTime()) RewriteTime updated to 1000ms
 2020-12-24T02:05:02.892Z [hyperiond LEDDEVICE] (DEBUG) (LedDeviceWS281x.cpp:59:init()) ws281x strip type : 1050624
 2020-12-24T02:05:02.906Z [hyperiond FLATBUFCONN] (INFO) Connecting to Hyperion: 127.0.0.1:19401
 2020-12-24T02:05:02.926Z [hyperiond HYPERION] (DEBUG) (PriorityMuxer.cpp:161:registerInput()) Register new input 'System/V4L' with priority 230 as inactive
 2020-12-24T02:05:02.927Z [hyperiond COMPONENTREG] (DEBUG) (ComponentRegister.cpp:36:setNewComponentState()) V4L capture device: enabled
 2020-12-24T02:05:03.147Z [hyperiond V4L2:/DEV/VIDEO0] (INFO) Multithreading for V4L2 is enabled. Available thread's count 4
 2020-12-24T02:05:03.150Z [hyperiond V4L2:/DEV/VIDEO0] (INFO) configured v4l device: /dev/video0
 2020-12-24T02:05:03.163Z [hyperiond V4L2:/DEV/VIDEO0] (INFO) Set resolution to: 1280 x 720
 2020-12-24T02:05:03.175Z [hyperiond V4L2:/DEV/VIDEO0] (INFO) Set framerate to 30 FPS
 2020-12-24T02:05:03.175Z [hyperiond V4L2:/DEV/VIDEO0] (DEBUG) (V4L2Grabber.cpp:100:GetSharedLut()) LUT folder location: '/usr/share/hyperion/lut'
 2020-12-24T02:05:03.176Z [hyperiond V4L2:/DEV/VIDEO0] (INFO) Pixel format: MJPEG
 2020-12-24T02:05:03.207Z [hyperiond V4L2:/DEV/VIDEO0] (INFO) Started
 2020-12-24T02:05:03.207Z [hyperiond V4L2:/dev/video0] (DEBUG) (GrabberWrapper.cpp:48:start()) Grabber start()
 2020-12-24T02:05:02.928Z [hyperiond BOBLIGHT] (DEBUG) (BoblightServer.cpp:28:BoblightServer()) Instance created
 2020-12-24T02:05:03.208Z [hyperiond HYPERION] (INFO) Hyperion instance 'Wled Den instance' has been started
 2020-12-24T02:05:02.928Z [hyperiond COMPONENTREG] (DEBUG) (ComponentRegister.cpp:36:setNewComponentState()) LED device: enabled
 2020-12-24T02:05:03.137Z [hyperiond FLATBUFSERVER] (INFO) Started on port 19400
 2020-12-24T02:05:03.143Z [hyperiond PROTOSERVER] (INFO) Started on port 19445
 2020-12-24T02:05:03.144Z [hyperiond WEBSERVER] (DEBUG) (WebServer.cpp:33:initServer()) Initialize Webserver
 2020-12-24T02:05:03.147Z [hyperiond WEBSERVER] (DEBUG) (WebServer.cpp:33:initServer()) Initialize Webserver
 2020-12-24T02:05:03.191Z [hyperiond HYPERION] (DEBUG) (PriorityMuxer.cpp:351:setCurrentTime()) Set visible priority to 255
 2020-12-24T02:05:03.191Z [hyperiond HYPERION] (DEBUG) (Hyperion.cpp:559:handlePriorityChangedLedDevice()) priority[255], previousPriority[255]
 2020-12-24T02:05:03.192Z [hyperiond HYPERION] (DEBUG) (Hyperion.cpp:562:handlePriorityChangedLedDevice()) No source left -> switch LED-Device off
 2020-12-24T02:05:03.194Z [hyperiond BLACKBORDER] (DEBUG) (ImageProcessor.cpp:156:setHardLedMappingType()) set hard led mapping to multicolor_mean
 2020-12-24T02:05:03.218Z [hyperiond WEBSERVER] (DEBUG) (WebServer.cpp:91:handleSettingsUpdate()) Apply Webserver settings
 2020-12-24T02:05:03.218Z [hyperiond WEBSERVER] (DEBUG) (WebServer.cpp:91:handleSettingsUpdate()) Apply Webserver settings
 2020-12-24T02:05:03.219Z [hyperiond WEBSERVER] (DEBUG) (WebServer.cpp:109:handleSettingsUpdate()) Set document root to: :/webconfig
 2020-12-24T02:05:03.219Z [hyperiond WEBSERVER] (DEBUG) (WebServer.cpp:109:handleSettingsUpdate()) Set document root to: :/webconfig
 2020-12-24T02:05:03.220Z [hyperiond WEBSERVER] (INFO) Started on port 8090 name 'Hyperion Webserver'
 2020-12-24T02:05:03.474Z [hyperiond V4L2:/DEV/VIDEO0] (DEBUG) (V4L2Grabber.cpp:1145:process_image()) Worker's thread count  = 4
 2020-12-24T02:05:03.498Z [hyperiond HYPERION] (DEBUG) (PriorityMuxer.cpp:251:setInputImage()) Priority 230 is now active
 2020-12-24T02:05:03.499Z [hyperiond HYPERION] (DEBUG) (PriorityMuxer.cpp:351:setCurrentTime()) Set visible priority to 230
 2020-12-24T02:05:03.516Z [hyperiond HYPERION] (DEBUG) (Hyperion.cpp:559:handlePriorityChangedLedDevice()) priority[230], previousPriority[255]
 2020-12-24T02:05:03.517Z [hyperiond HYPERION] (DEBUG) (Hyperion.cpp:569:handlePriorityChangedLedDevice()) new source available -> switch LED-Device on
 2020-12-24T02:05:03.517Z [hyperiond BLACKBORDER] (DEBUG) (ImageProcessor.cpp:156:setHardLedMappingType()) set hard led mapping to multicolor_mean
 2020-12-24T02:05:03.551Z [hyperiond WEBSERVER] (DEBUG) (WebServer.cpp:175:handleSettingsUpdate()) Setup SSL certificate
 2020-12-24T02:05:03.552Z [hyperiond WEBSERVER] (DEBUG) (WebServer.cpp:191:handleSettingsUpdate()) Setup private SSL key
 2020-12-24T02:05:03.552Z [hyperiond WEBSERVER] (INFO) Started on port 8092 name 'Hyperion Webserver'
 2020-12-24T02:05:06.891Z [hyperiond WEBSOCKET] (DEBUG) (WebSocketClient.cpp:30:WebSocketClient()) New connection from ::ffff:192.168.1.33
 2020-12-24T02:05:06.892Z [hyperiond WEBSOCKET] (DEBUG) (JsonAPI.cpp:85:handleInstanceSwitch()) Client '::ffff:192.168.1.33' switch to Hyperion instance 0
 2020-12-24T02:05:46.454Z [hyperiond HYPERION] (DEBUG) (PriorityMuxer.cpp:251:setInputImage()) Priority 230 is now inactive
 2020-12-24T02:05:46.457Z [hyperiond HYPERION] (DEBUG) (PriorityMuxer.cpp:351:setCurrentTime()) Set visible priority to 255
 2020-12-24T02:05:46.458Z [hyperiond HYPERION] (DEBUG) (Hyperion.cpp:559:handlePriorityChangedLedDevice()) priority[255], previousPriority[230]
 2020-12-24T02:05:46.458Z [hyperiond HYPERION] (DEBUG) (Hyperion.cpp:562:handlePriorityChangedLedDevice()) No source left -> switch LED-Device off
 2020-12-24T02:05:47.088Z [hyperiond BLACKBORDER] (DEBUG) (ImageProcessor.cpp:156:setHardLedMappingType()) set hard led mapping to multicolor_mean
 2020-12-24T02:05:47.120Z [hyperiond HYPERION] (DEBUG) (PriorityMuxer.cpp:251:setInputImage()) Priority 230 is now active
 2020-12-24T02:05:47.120Z [hyperiond HYPERION] (DEBUG) (PriorityMuxer.cpp:351:setCurrentTime()) Set visible priority to 230
 2020-12-24T02:05:47.123Z [hyperiond HYPERION] (DEBUG) (Hyperion.cpp:559:handlePriorityChangedLedDevice()) priority[230], previousPriority[255]
 2020-12-24T02:05:47.124Z [hyperiond HYPERION] (DEBUG) (Hyperion.cpp:569:handlePriorityChangedLedDevice()) new source available -> switch LED-Device on
 2020-12-24T02:05:47.124Z [hyperiond BLACKBORDER] (DEBUG) (ImageProcessor.cpp:156:setHardLedMappingType()) set hard led mapping to multicolor_mean
 2020-12-24T02:05:56.377Z [hyperiond COMPONENTREG] (DEBUG) (ComponentRegister.cpp:36:setNewComponentState()) Smoothing: disabled
 2020-12-24T02:06:03.147Z [hyperiond V4L2:/DEV/VIDEO0] (DEBUG) (V4L2Grabber.cpp:1137:process_image()) Video FPS: 28.97, av. delay: 21ms, good: 1676, bad: 62 (60.00,15)
 2020-12-24T02:06:45.153Z [hyperiond WEBSOCKET] (DEBUG) (JsonAPI.cpp:1087:handleLoggingCommand()) log streaming activated for client ::ffff:192.168.1.33

**Comment by awawa-dev** [comment] 2020-12-24 11:30
Log seems OK although you are using now ws281x led strip instead of Philips Hue from the previous report.

**Comment by Bboy486** [comment] 2020-12-24 16:22
I always had the ws281x as instance 1 (main instance) the hue were instance 2 but I deleted those. Whites are still off on pure white backgrounds though.

**Comment by awawa-dev** [comment] 2020-12-24 16:51
As I cant see any more errors here and guessing that the second instance is working can only recommend to use "processing tab" to calibrate colors.

**Comment by awawa-dev** [comment] 2021-03-01 20:35
Closed as I cant reproduce or analyze the problem due to lack of more details. One of out of gamut situation for Philips driver is fixed in new v15 but I doubt it's related.

**Closed by awawa-dev** 2021-03-01 20:35 UTC
