### ISSUE TITLE
Virtual Audio Cable Output Reading Silent as Sound Capture Device

### ISSUE THREAD

**Issue by chdgriff** [awawa-dev/HyperHDR#112] opened 2021-08-29 23:39 UTC
## Bug report, debug log and your config file (FULL LOGS ARE MANDATORY)

Logs: https://pastebin.com/NcjtQ38G
Config: https://pastebin.com/XgVJieah

I am trying to use the https://vb-audio.com/Cable/ as a sound capture device for music visualization.

#### Steps to reproduce
1. Direct Audio Source towards Virtual Audio Cable Input
2. Select Virtual Cable Out as sound capture device for effects
3. Choose any Music Visualization effect from the Remote Control

#### What is expected?
Audio data should be correctly captured and visualized from the Virtual Audio Cable Output.

#### What is actually happening?
Log Warning: "Sound stream: captured audio data but it's silence." I can see audio activity in the Windows sound control panel and other applications are able to correctly handle the virtual audio cable so I don't think its the virtual audio cable.

#### System
HyperHDR Server: 
- Build:           (HEAD detached at 6e22b3f) (Awawa-6485055/6e22b3f-1621524301)
- Build time:      May 20 2021 16:04:07
- Git Remote:      https://github.com/awawa-dev/HyperHDR
- Version:         16.0.0.1
- UI Lang:         en (BrowserLang: en-US)
- UI Access:       expert
- Avail Capt:      Windows (Microsoft Media Foundation)
- Database:        read/write

HyperHDR Server OS: 
- Distribution:   Windows 10 Version 2009
- Architecture:   x86_64
- Kernel:         winnt (10.0.19043 (WS: 64))
- Qt Version:     5.15.2
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36

**Comment by awawa-dev** [comment] 2021-08-29 23:45
````2021-08-29T23:19:57.328Z [HYPERHDR] (WARNING) Sound stream: captured audio data but it's silence.````
Since the driver you have selected provides no sound (only zeroes, that's why you see that message in the log) then we can do nothing about it.  
It's noted in the manual why it may happen.

**Comment by awawa-dev** [comment] 2021-08-29 23:53
For windows we use format: one channel, 22050 probes/sec, 16 bits per probe driver. Maybe it's not supported?

**Comment by chdgriff** [comment] 2021-08-29 23:59
> `2021-08-29T23:19:57.328Z [HYPERHDR] (WARNING) Sound stream: captured audio data but it's silence.`
> Since the driver you have selected provides no sound (only zeroes, that's why you see that message in the log) then we can do nothing about it.
> It's noted in the manual why it may happen: https://hyperhdr.blogspot.com/2021/04/how-to-set-up-hyperhdr-part-i-basic.html#chapter6

I can confirm there is sound on the virtual audio cable. Windows sound control panel, obs, ledfx, or any other application reads the virtual audio device perfectly.

> For windows we use format: one channel, 22050 probes/sec, 16 bits per probe driver. Maybe it's not supported?

The virtual audio cable is set to 2 channel, 48000 Hz, 24 bit output so maybe that is the issue?

**Comment by awawa-dev** [comment] 2021-08-30 00:08
Maybe that's the limitation. But there is an error handling check in the sound grabber anyway: the driver accept our audio stream format with no error and later it provides data: but only zeroes. It's hard to extrapolate proper audio from them ;-)  
Unfortunately that format is unified between all the system and can't be easily changed since the weakest device (Raspberry Pi) should be able to process audio data. And hardware video grabbers that we tested on different OS... their drivers have no problem with providing sound in that format.

**Comment by chdgriff** [comment] 2021-08-30 00:37
Tried lowering the virtual audio device to it's lowest quality of 1 channel, 16bit 8000hz and still a no go.

I guess this is a limitation of HyperHDR of not being able to accept this audio device. Maybe I'll have a look at the source to try and figure out why the audio grabber can't parse this functioning audio device.

**Comment by awawa-dev** [comment] 2021-08-30 00:50
The problem lies in the data that are incoming. Simply, I tried to explain it better why I closed it. So far nothing indicates anything else but that virtual driver. Unless more data will be provided, for now it is not enough for me to analyze it further.
  
The HyperHDR sound driver handling for Windows is small one:
https://github.com/awawa-dev/HyperHDR/blob/master/libsrc/grabber/SoundCapWindows/SoundCapWindows.cpp
format is set around line 76
  
you can set a break-point in the soundInProc and analyze it further when audio data arrives: line 37
  
Maybe you will find exactly what happens on your setup and then maybe we can find a solution.

**Comment by chdgriff** [comment] 2021-08-30 01:07
I can always provide more data or information on request

**Comment by awawa-dev** [comment] 2021-08-30 01:12
OK, let's try then for some time.
And here is that unfortunate procedure that checks if the audio is coming. Don't need to debug...if something above 8 or below -8 then we have sound (quite small values for full range int16_t ):
https://github.com/awawa-dev/HyperHDR/blob/d1d10c8709399a77701d483278a3b39ea2541b35/libsrc/hyperhdrbase/SoundCapture.cpp#L254

**Comment by awawa-dev** [comment] 2021-09-04 12:26
After regression testing of version 17 for Windows:
- still all my 4 tested USB grabbers works with sound capturing, audio effects also works.
- this time I was not limited myself to the USB grabbers. Also tested headphone set. Works OK as on the screenshot.
![obraz](https://user-images.githubusercontent.com/69086569/132094070-82476a69-abc0-4914-b4d1-e54cac2457e5.png)
- diagnosis is the same as at the beginning (thanks to built-in HyperHDR stream validation mechanisms): faulty 3-rd party virtual sound driver with no capabilities to provide us data as we requested and despite that: reporting no error (or it's badly configured Windows sound mixer, it should be obvious) ... but it's easier to blame us. Nevertheless it was tested just in case so I'm closing the issue.

**Closed by awawa-dev** 2021-09-04 12:26 UTC
Labels: no HyperHDR issue
