### ISSUE TITLE
Philips Hue Assistant Save Button not working

### ISSUE THREAD

**Issue by HorizonKane** [awawa-dev/HyperHDR#552] opened 2023-04-13 07:57 UTC
#### Steps to reproduce
- Start Hue assistant
- Generate User / Key
- Choose Entertainment group
- Setup lights
- Press Save

#### What is expected?
That the assistant closes and saves the configuration.

#### What is actually happening?
Nothing. 

I tried it in Firefox on my Laptop and Chrome on my Smartphone.

#### System

HyperHDR Server: 
- Build:           (HEAD detached at v19.0.0.0) (Awawa-3141e80/b8c7f04-1676222403)
- Build time:      Feb 12 2023 17:40:44
- Git Remote:      https://github.com/awawa-dev/HyperHDR
- Version:         19.0.0.0
- UI Lang:         auto (BrowserLang: de)
- UI Access:       default
- Avail Capt:      Linux (V4L2)
- Database:        read/write

HyperHDR Server OS: 
- Distribution:   Debian GNU/Linux 11 (bullseye)
- Architecture:   arm64
- CPU Type:       Raspberry Pi 4 Model B Rev 1.1
- CPU Revision:   c03111
- CPU Hardware:   BCM2835
- Kernel:         linux (5.15.84-v8+ (WS: 64))
- Qt Version:     5.15.2
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0

**Comment by awawa-dev** [comment] 2023-04-13 09:17
Hi
It's working just fine in v19 or provide full and detail path to reproduce the problem for example https://github.com/awawa-dev/HyperHDR/discussions/512 No mandatory logs either so closing

**Closed** 2023-04-13 09:18 UTC

**Comment by firstone** [comment] 2025-01-31 02:48
I've had same issue with 21.0.0.0beta1. No errors in the log but there was some undefined error in chrome developer console. Started working after restart of service.

**Comment by awawa-dev** [comment] 2025-01-31 10:34
@firstone If you don't have logs (and they would be useful because even without errors they described the state before using the wizard...) then a description of the repeatable path that led to such a situation and a screen of errors from the browser console would be useful. Maybe you can repeat it by resetting the configuration? Without such information I will absolutely not be able to track it down because I tested it myself and I do not have any such error.
