### ISSUE TITLE
The LED device toggle turns off the WLED device too

### ISSUE THREAD

**Issue by fallenruby** [awawa-dev/HyperHDR#200] opened 2022-01-30 00:36 UTC
Hi! I know that probably this is intended behavior, but this is my scenario:

1. I have my WLED device on (not running hyper hdr: just as an ambient light behind the TV)
2. Then I will begin watching a show and turn on Hyper HDR (LED device to ON via the GUI, Remote Control - Components - LED Device)
3. Show's over: I turn OFF the LED device via Hyper HDR, and the WLED device will turn off too

Could be possible to not turn off the WLED device, maybe via a setting, if that was previously on?

Thanks

**Comment by awawa-dev** [comment] 2022-01-30 13:30
Hi
Yes it's intended behavior. Some HyperHDR's LED network drivers can preserve initial lamps state (Philips Hue driver), others like WLED currently can't. But I think it's possible to implement such behavior for WLED network driver too.

**Comment by fallenruby** [comment] 2022-02-01 18:39
WLED's JSON API will return **on = true** if the device is, in fact, on. The endpoint is /json/state 

[https://kno.wled.ge/interfaces/json-api/](https://kno.wled.ge/interfaces/json-api/)

**Comment by awawa-dev** [comment] 2022-02-01 21:35
Thanks. Still don't know what happen even if we leave the lamp controller by WLED just enabled (after turning WLED instance off in HyperHDR)? Colors don't matter? They are not restored and it's enough?

**Comment by fallenruby** [comment] 2022-02-17 19:56
I'm so sorry for the late reply -

The colors should remain the same:
when the wled device is OFF settings are preserved (colors):

`{
    **"on": false,**
    "bri": 255,
    "transition": 7,
    "ps": -1,
    "pss": 0,
    "pl": -1,
    "ccnf": {
        "min": 1,
        "max": 5,
        "time": 12
    },
    "nl": {
        "on": false,
        "dur": 60,
        "fade": true,
        "mode": 1,
        "tbri": 0,
        "rem": -1
    },
    "udpn": {
        "send": true,
        "recv": true
    },
    "lor": 0,
    "mainseg": 0,
    "seg": [
        {
            "id": 0,
            "start": 0,
            "stop": 236,
            "len": 236,
            "grp": 1,
            "spc": 0,
            "on": true,
            "bri": 255,
            **"col": [
                [
                    255,
                    160,
                    0
                ],**
                [
                    0,
                    0,
                    0
                ],
                [
                    0,
                    0,
                    0
                ]
            ],
            "fx": 0,
            "sx": 128,
            "ix": 128,
            "pal": 0,
            "sel": true,
            "rev": false,
            "mi": false
        }
    ]
}`

The problem is, that the "LED device" toggle in Remote Control, is not synced with the WLED device

WLED API:
`"components": [
            {
                "enabled": true,
                "name": "ALL"
            },
            {
                "enabled": false,
                "name": "HDR"
            },
            {
                "enabled": true,
                "name": "SMOOTHING"
            },
            {
                "enabled": false,
                "name": "BLACKBORDER"
            },
            {
                "enabled": false,
                "name": "FORWARDER"
            },
            {
                "enabled": false,
                "name": "BOBLIGHTSERVER"
            },
            {
                "enabled": true,
                "name": "VIDEOGRABBER"
            },
            {
                "enabled": false,
                "name": "SYSTEMGRABBER"
            },
            {
                **"enabled": true,
                "name": "LEDDEVICE"**
            }
        ],`

BUT, on second thought, the LED Device toggle isn't wrong at all (I can turn off the WLED device from HyperHDR GUI)

The "problem" IMHO is in the Instance too: 
when I disable my 'Ambilight' instance, HyperHDR turns off my WLED device too

HYPERHDR API:
`            {
                **"enabled": false,**
                "name": "LEDDEVICE"
            }`

Wrapping up
_Component_ LEDDEVICE from HyperHDR seems not to consider the real state of the WLED device. 
 Disabling an instance should not turn off _Component_ LEDDEVICE if it's ON

Thank you for your time

**Comment by awawa-dev** [comment] 2022-03-13 17:55
Unless somebody propose detail diagram how such functionality should behave (includes which option triggers some new behavior and how to invoke specific WLED API functionality or to store them) then I'm closing the feature request. Currently I don't see how this would work. Currently I'm not PR is welcome.

**Closed** 2022-04-03 13:58 UTC
Labels: feature request

**Comment by awawa-dev** [comment] 2022-09-19 19:15
https://github.com/awawa-dev/HyperHDR/pull/353
