### ISSUE TITLE
Nanoleaf 4D Lightstrip error

### ISSUE THREAD

**Issue by mayorgergich** [awawa-dev/HyperHDR#909] opened 2024-07-18 16:21 UTC
https://pastebin.com/7rmbYcLy

## Bug report, debug log and your config file (FULL LOGS ARE MANDATORY)
https://pastebin.com/7rmbYcLy

#### Steps to reproduce

1. Add Nanoleaf as LED Controller and set number of LEDs. Nanoleaf being used is Nanoleaf 4D.

#### What is expected?
LED light sync using Nanoleaf 4D Light Strip

#### What is actually happening?
Nothing. Logs indicate that the number of panels is insufficient but no panels are being used.
#### System

HyperHDR status:
On
Platform:
macOS (AVF)
Video device
Video mode
Controller type:
nanoleaf
Instance:
HyperHDR
Your HyperHDR version:
20.0.0.0
Latest HyperHDR version:
v20.0.0.0

**Comment by awawa-dev** [comment] 2024-07-18 16:24
Hi
Since I dont have Nanoleaf 4D device, I cannot implement it. So it means Nanoleaf 4D is not supported at the moment.

**Comment by mayorgergich** [comment] 2024-07-18 16:29
Thank you. Do other Nanoleaf strips work, or only panels?

**Comment by awawa-dev** [comment] 2024-07-18 16:37
Since this is a niche solution and I don't have any of them to conduct regression tests, in subsequent versions of HyperHDR we rely only on feedback from the community and it suggests that the panels work.

**Comment by awawa-dev** [comment] 2024-08-02 12:36
Hi
Are you interested in testing a version with some changes for Nanoleaf 4D or can we close this ticket?

**Comment by mayorgergich** [comment] 2024-08-03 19:33
Hi. I ended up changing the light. This can be closed.

Sent via Superhuman iOS ( ***@***.*** )

**Closed** 2024-08-04 14:56 UTC
