### ISSUE TITLE
Crash - SIGABRT: malloc_consolidate(): invalid chunk size

### ISSUE THREAD

**Issue by FransTwisk** [awawa-dev/HyperHDR#23] opened 2021-01-05 21:58 UTC
Today my Ambilight didn't work for first time in weeks. Webinterface of HyperHDR was unreachable so couldn't get to any logs. This is all I could find:

```
hyperiond@pi.service - Hyperion ambient light systemd service  for user pi
   Loaded: loaded (/etc/systemd/system/hyperiond@.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2020-12-29 18:33:25 CET; 1 weeks 0 days ago
 Main PID: 13262 (hyperiond)
    Tasks: 16 (limit: 4915)
   CGroup: /system.slice/system-hyperiond.slice/hyperiond@pi.service
           └─13262 /usr/bin/hyperiond

Jan 05 13:17:54 pi4 hyperiond[13262]: malloc_consolidate(): invalid chunk size
Jan 05 13:17:54 pi4 hyperiond[13262]: Hyperion caught signal :SIGABRT
```

It seems to work fine again after restart.

#### Hardware
Pi4 4Gb running latest Raspberry OS
HyperHDR v14.0.0.0
WLED Controller Type
[USB HDMI Grabber](https://www.amazon.nl/gp/product/B08C9Z5BD2/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1)

#### System
HyperHDR Server: 
- Build:           (HEAD detached at d35314e) (GitHub-9795cc8/d35314e-1608750238)
- Build time:      Dec 23 2020 20:19:43
- Git Remote:      https://github.com/awawa-dev/HyperHDR
- Version:         14.0.0.0
- UI Lang:         auto (BrowserLang: en-GB)
- UI Access:       expert
- Avail Capt:      v4l2
- Database:        read/write

HyperHDR Server OS: 
- Distribution:   Raspbian GNU/Linux 10 (buster)
- Architecture:   arm
- CPU Model:      ARMv7 Processor rev 3 (v7l)
- CPU Type:       Raspberry Pi 4 Model B Rev 1.2
- CPU Revision:   c03112
- CPU Hardware:   BCM2711
- Kernel:         linux (5.4.79-v7l+ (WS: 32))
- Qt Version:     5.11.3
- Python Version: 3.7.3
- Browser:        Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.101 Safari/537.36

**Comment by awawa-dev** [comment] 2021-01-05 22:14
Did you run some action just before the crash for ex. change the resolution or some other setting? Did you use the live video preview in the WWW then?

**Comment by FransTwisk** [comment] 2021-01-06 08:19
No, I wasn't using the webinterface at all. Hardly touching it. It just runs on my Pi which is always on and yesterday the LEDs suddenly just didn't respond anymore. I don't know what I was doing around 13:17:54 because my WLED only turns on when the sun is down, so didn't notice it at the time it crashed. So not much info, but wanted to share it anyway.

**Comment by awawa-dev** [comment] 2021-01-06 10:13
OK, thanks anyway. After reviewing code related to that crash (around 'free' and memory allocation) I found some inconsistency in one, quite important module. But I'm not sure if that was the cause of that crash.

**Comment by FransTwisk** [comment] 2021-01-07 09:40
If there is any way I can provide you with more logs, let me know. I don't know where to find the logs expect through the webinterface, which is kind of useless when it crashes. Any way to log this to a file?

**Comment by awawa-dev** [comment] 2021-01-07 18:52
You can run it not as a service/deamon but execute "/usr/bin/hyperiond -d" instead and leave it for example under "screen" or redirect output to the file.

**Comment by FransTwisk** [comment] 2021-01-16 10:39
Had the same happening yesterday. Mighy have been exactly at the point I turned on my TV + Receiver with HDMI grabber on one of the monitors. Not sure since again I discovered later it has crashed.

**Comment by awawa-dev** [comment] 2021-01-16 12:43
Please compile HyperHDR in the debug (not default release) mode, run it as a program (not service) and attach log to this report when/if that crash happens. Maybe that would provide come clues. HyperHDR is a complex. multi-threaded program that uses many external and system internal components. As I'm unable to reproduce it on my systems (both linux and windows, maybe your unique configuration or running service for a few days play some part in it) searching for possible reason is like searching for a needle in a haystack. As you can see chances for succeed are slim and as it's a very rare problem I'd prefer to spend my resources to implement new features. And as I checked in valgrind there is no obvious memory leak/access in the HyperHDR itself.

**Comment by FransTwisk** [comment] 2021-01-16 14:16
I completely understand. I just never have compiled it myself and don't really know how to do this, but will look into it.

**Comment by awawa-dev** [comment] 2021-01-16 15:02
Instruction are here: [https://github.com/awawa-dev/HyperHDR/blob/master/CompileHowto.md](https://github.com/awawa-dev/HyperHDR/blob/master/CompileHowto.md)
1 After preparing build environment  & download sources from git (as per the instruction, before building) you must stop HyperHDR service. It MUST NOT be running all the time
` sudo systemctl stop hyperiond@pi.service`
2 configure project in DEBUG mode (assume that you are in the _build_ folder as per instruction)
`cmake -DCMAKE_BUILD_TYPE=Debug ..`
3 make it:
`make -j $(nproc)`
4 run it and wait for possible crash, then log the output from the console:
`bin/hyperiond -d`
or redirect output to the file for example: /bin/hyperiond -d > /tmp/hyperhdr.log
5 ssh terminal must be opened all the time. Otherwise after disconnecting that process is killed. To overcome this you can use standard Linux util: '_screen_'

**Comment by awawa-dev** [comment] 2021-03-01 20:43
Any new update? There is new v15 that fixes critical errors that I met in some places so maybe you could give it a try?

**Comment by FransTwisk** [comment] 2021-03-02 16:30
The issue has not appeared again, so it's probably some weird edge-case scenario. I will install the new version nonetheless.

**Comment by dinacel** [comment] 2021-05-15 08:41
I'm not sure it's related but this what I have after an HA command:
```
May 14 21:52:35 hyperhdr hyperhdr[28092]: 2021-05-14T21:52:35.087 V4L2:AUTO              : <INFO> Video FPS: 20.02, av. delay: 64ms, good: 1201, bad: 0 (60.04,15)
May 14 21:52:51 hyperhdr hyperhdr[28092]: 2021-05-14T21:52:51.871 HYPERHDR               : <DEBUG> PriorityMuxer.cpp:162:registerInput() | Register new input 'Home Assistant@::ffff:192.168.1.14/COLOR' with priority 128 as inactive
May 14 21:52:51 hyperhdr hyperhdr[28092]: 2021-05-14T21:52:51.872 HYPERHDR               : <DEBUG> PriorityMuxer.cpp:208:setInput() | Priority 128 is now active
May 14 21:52:51 hyperhdr hyperhdr[28092]: 2021-05-14T21:52:51.872 HYPERHDR               : <DEBUG> PriorityMuxer.cpp:378:setCurrentTime() | Set visible priority to 128
May 14 21:52:51 hyperhdr hyperhdr[28092]: 2021-05-14T21:52:51.872 HYPERHDR               : <DEBUG> HyperHdrInstance.cpp:550:handlePriorityChangedLedDevice() | priority[128], previousPriority[240]
May 14 21:52:51 hyperhdr hyperhdr[28092]: 2021-05-14T21:52:51.873 IMAGETOLED             : <DEBUG> ImageProcessor.cpp:180:setHardLedMappingType() | set hard led mapping to multicolor_mean
May 14 21:52:51 hyperhdr hyperhdr[28092]: QJson: Document too large to store in data structure
May 14 21:52:51 hyperhdr hyperhdr[28092]: malloc(): unsorted double linked list corrupted
May 14 21:52:51 hyperhdr hyperhdr[28092]: Hyperion caught signal :SIGABRT
```

Web UI was stuck after that and I had to restart the HyperHDR daemon.

**Comment by awawa-dev** [comment] 2021-05-15 11:04
Don't know if it's related either. Seems there is no defense on external data overload or an incompatible structure was sent and it should be done better in HyperHDR. Could you provide me more information about a path to reproduce the problem using HA?

**Closed** 2021-05-25 23:50 UTC

**Comment by ztnel** [comment] 2022-01-11 02:15
Don't mean to reopen a can of worms but I may be able to provide more information on this problem. I encountered the same error when upgrading my capture card. I tried restarting the service but it did not help. From my `dmesg` logs the issue may be a result of a failed capture card initialization.

### Environment:
RPi4 Model B
OS: 32-bit rasbian lite (Linux raspberrypi 5.10.17-v7l+ #1414 SMP Fri Apr 30 13:20:47 BST 2021 armv7l GNU/Linux)
WS218x PWM Driver

### Logs
Here is my `journalctl`:
```bash
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.695 hyperiond JSONSERVER   : <DEBUG> JsonServer.cpp:28:JsonServer() | Created instance
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.696 hyperiond JSONSERVER   : <INFO> Started on port 19444
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.702 hyperiond LEDDEVICE    : <INFO> Start LedDevice 'ws281x'.
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.702 hyperiond LEDDEVICE    : <DEBUG> LedDevice.cpp:148:init() | deviceConfig: [{"colorOrder":"grb","currentLedCount":183,"dma":10,"gpio":1
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.702 hyperiond LEDDEVICE    : <DEBUG> LedDevice.cpp:413:setLatchTime() | LatchTime updated to 0ms
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.702 hyperiond LEDDEVICE    : <DEBUG> LedDevice.cpp:438:setRewriteTime() | Refresh interval = 1000ms
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.703 hyperiond LEDDEVICE    : <DEBUG> LedDevice.cpp:444:setRewriteTime() | RewriteTime updated to 1000ms
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.703 hyperiond LEDDEVICE    : <DEBUG> LedDeviceWS281x.cpp:65:init() | ws281x strip type : 1050624
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.703 hyperiond COMPONENTREG : <DEBUG> ComponentRegister.cpp:41:setNewComponentState() | Smoothing: enabled
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.703 hyperiond SMOOTHING    : <DEBUG> LinearColorSmoothing.cpp:687:selectConfig() | cfg [0]:  Type: linear - Time: 200 ms, outputRate 25.00
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.704 hyperiond FLATBUFSERVE : <INFO> Started on port 19400
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.704 hyperiond SMOOTHING    : <DEBUG> LinearColorSmoothing.cpp:687:selectConfig() | Previous line repeats 1 times
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.705 hyperiond FLATBUFCONN  : <INFO> Connecting to Hyperion: 127.0.0.1:19401
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.706 hyperiond PROTOSERVER  : <INFO> Started on port 19445
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.707 hyperiond EFFECTENGINE : <INFO> Run effect "Rainbow swirl fast" on channel 1
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.708 hyperiond EFFECTENGINE : <DEBUG> EffectEngine.cpp:181:runEffectScript() | Start the effect: name [Rainbow swirl fast], smoothCfg [2]
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.708 hyperiond HYPERION     : <DEBUG> PriorityMuxer.cpp:165:registerInput() | Register new input 'System/EFFECT' with priority 1 as inactiv
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.708 hyperiond HYPERION     : <INFO> Initial foreground effect 'Rainbow swirl fast' started
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.709 hyperiond EFFECTENGINE : <INFO> Run effect "Fire" on channel 254
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.709 hyperiond EFFECTENGINE : <DEBUG> EffectEngine.cpp:181:runEffectScript() | Start the effect: name [Fire], smoothCfg [2]
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.709 hyperiond HYPERION     : <DEBUG> PriorityMuxer.cpp:165:registerInput() | Register new input 'System/EFFECT' with priority 254 as inact
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.709 hyperiond HYPERION     : <INFO> Initial background effect 'Fire' started
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.710 hyperiond HYPERION     : <DEBUG> PriorityMuxer.cpp:165:registerInput() | Register new input 'System/V4L' with priority 240 as inactive
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.710 hyperiond COMPONENTREG : <DEBUG> ComponentRegister.cpp:41:setNewComponentState() | V4L capture device: enabled
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.711 hyperiond BOBLIGHT     : <DEBUG> BoblightServer.cpp:28:BoblightServer() | Instance created
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.711 hyperiond COMPONENTREG : <DEBUG> ComponentRegister.cpp:41:setNewComponentState() | LED device: enabled
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.712 hyperiond WEBSERVER    : <DEBUG> WebServer.cpp:33:initServer() | Initialize Webserver
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.714 hyperiond HYPERION     : <INFO> Hyperion instance 'ws281x' has been started
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.715 hyperiond WEBSERVER    : <DEBUG> WebServer.cpp:33:initServer() | Initialize Webserver
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.734 hyperiond WEBSERVER    : <DEBUG> WebServer.cpp:91:handleSettingsUpdate() | Apply Webserver settings
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.734 hyperiond WEBSERVER    : <DEBUG> WebServer.cpp:109:handleSettingsUpdate() | Set document root to: :/webconfig
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.736 hyperiond WEBSERVER    : <DEBUG> WebServer.cpp:109:handleSettingsUpdate() | Set document root to: :/webconfig
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.737 hyperiond WEBSERVER    : <INFO> Started on port 8090 name 'Hyperion Webserver'
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.738 hyperiond WEBSERVER    : <DEBUG> WebServer.cpp:175:handleSettingsUpdate() | Setup SSL certificate
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.738 hyperiond WEBSERVER    : <DEBUG> WebServer.cpp:191:handleSettingsUpdate() | Setup private SSL key
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.739 hyperiond WEBSERVER    : <INFO> Started on port 8092 name 'Hyperion Webserver'
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.804 hyperiond HYPERION     : <DEBUG> PriorityMuxer.cpp:271:setInputImage() | Priority 1 is now active
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.805 hyperiond HYPERION     : <DEBUG> BGEffectHandler.h:91:handlePriorityUpdate() | Stop background (color-) effect as it moved out of scop
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.805 hyperiond HYPERION     : <DEBUG> PriorityMuxer.cpp:292:clearInput() | Removed source priority 254
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.805 hyperiond EFFECTENGINE : <INFO> Run effect "Fire" on channel 254
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.805 hyperiond EFFECTENGINE : <DEBUG> EffectEngine.cpp:181:runEffectScript() | Start the effect: name [Fire], smoothCfg [2]
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.805 hyperiond HYPERION     : <DEBUG> PriorityMuxer.cpp:165:registerInput() | Register new input 'System/EFFECT' with priority 254 as inact
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.805 hyperiond HYPERION     : <INFO> Initial background effect 'Fire' started
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.805 hyperiond HYPERION     : <DEBUG> PriorityMuxer.cpp:374:setCurrentTime() | Set visible priority to 1
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.806 hyperiond SMOOTHING    : <DEBUG> LinearColorSmoothing.cpp:687:selectConfig() | cfg [2]:  Type: linear - Time: 200 ms, outputRate 25.00
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.806 hyperiond HYPERION     : <DEBUG> Hyperion.cpp:566:handleSourceAvailability() | priority[1], previousPriority[255]
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.806 hyperiond HYPERION     : <DEBUG> Hyperion.cpp:577:handleSourceAvailability() | new source available -> Resume output processing and sw
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.807 hyperiond HYPERION     : <DEBUG> BGEffectHandler.h:91:handlePriorityUpdate() | Stop background (color-) effect as it moved out of scop
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.807 hyperiond HYPERION     : <DEBUG> PriorityMuxer.cpp:292:clearInput() | Removed source priority 254
Jan 11 02:02:00 raspberrypi hyperiond[1933]: Hyperion caught signal :SIGSEGV
Jan 11 02:02:00 raspberrypi hyperiond[1933]: 2022-01-11T02:02:00.816 hyperiond CORE         : <ERROR>         /lib/arm-linux-gnueabihf/libc.so.6(__default_rt_sa_restorer+0) [0xb540c130]
Jan 11 02:02:00 raspberrypi hyperiond[1933]: malloc_consolidate(): invalid chunk size
Jan 11 02:02:00 raspberrypi hyperiond[1933]: Hyperion caught signal :SIGABRT
```

Here is my `dmesg`: 
```bash
[  236.912326] usb 1-1-port3: Cannot enable. Maybe the USB cable is bad?
[  238.262367] usb 1-1-port3: Cannot enable. Maybe the USB cable is bad?
[  238.262972] usb 1-1-port3: attempt power cycle
[  241.622301] usb 1-1-port3: Cannot enable. Maybe the USB cable is bad?
[  242.972317] usb 1-1-port3: Cannot enable. Maybe the USB cable is bad?
[  242.972922] usb 1-1-port3: attempt power cycle
[  246.332278] usb 1-1-port3: Cannot enable. Maybe the USB cable is bad?
[  247.682242] usb 1-1-port3: Cannot enable. Maybe the USB cable is bad?
[  247.682848] usb 1-1-port3: attempt power cycle
[  251.042219] usb 1-1-port3: Cannot enable. Maybe the USB cable is bad?
[  252.392252] usb 1-1-port3: Cannot enable. Maybe the USB cable is bad?
[  252.392858] usb 1-1-port3: attempt power cycle
[  255.752203] usb 1-1-port3: Cannot enable. Maybe the USB cable is bad?
[  257.102175] usb 1-1-port3: Cannot enable. Maybe the USB cable is bad?
[  257.102819] usb 1-1-port3: attempt power cycle
[  260.462119] usb 1-1-port3: Cannot enable. Maybe the USB cable is bad?
[  261.812208] usb 1-1-port3: Cannot enable. Maybe the USB cable is bad?
[  261.812819] usb 1-1-port3: attempt power cycle
[  265.172251] usb 1-1-port3: Cannot enable. Maybe the USB cable is bad?
[  266.522221] usb 1-1-port3: Cannot enable. Maybe the USB cable is bad?
[  266.522823] usb 1-1-port3: attempt power cycle
[  269.892353] usb 1-1-port3: Cannot enable. Maybe the USB cable is bad?
[  271.242396] usb 1-1-port3: Cannot enable. Maybe the USB cable is bad?
[  271.243430] usb 1-1-port3: attempt power cycle
```

**Comment by awawa-dev** [comment] 2022-01-11 08:47
@ztnel I doubt since it's not even log from HyperHDR.
