### ISSUE TITLE
Restarts Windows with no warning

### ISSUE THREAD

**Issue by dazedcrazy** [awawa-dev/HyperHDR#44] opened 2021-03-07 12:56 UTC
#### Steps to reproduce
Install on Windows
#### What is expected?
Prompt for restart or mention about forcing restart after install
#### What is actually happening?
Forces the system to restart without warning
#### System
Windows 10

I didn't have anything open that needed to be saved but I'd expect some people would be annoyed if they were testing this and it restarts their machine without asking.

**Comment by awawa-dev** [comment] 2021-03-07 13:04
Sorry, can not reproduce it. No forced restart. Even if the Microsoft VS C++ component somehow required restart it's not possible without user consent due to system security policy.

**Comment by dazedcrazy** [comment] 2021-03-07 13:44
I had it happen a few days while setting things up on my desktop and then again this morning while installing it on my server. Uninstalling and reinstalling doesn't make it restart though.

I didn't get to this dialog both time it just restarted
![image](https://user-images.githubusercontent.com/9027988/110241874-1bc37080-7f4b-11eb-9549-3868043dcfcb.png)

**Comment by awawa-dev** [comment] 2021-03-07 14:00
During installation of HyperHDR there's Microsoft VC++ component installed in a background: that's the only thing that comes to my mind. Do you have latest build of Windows 10 installed (which version)? Maybe some other running application that uses the library block the installation?
As I checked in the source currently MVC installation is executed as: ````vc_redist.x64.exe /install /quiet````
Probable changing it to: ````vc_redist.x64.exe /install /quiet /norestart```` would fix that situation and will try to commit later. Unfortunately as you can see it's hard to verify the solution as it's a first installation problem. So Windows 10 build version (and installed & running apps that come to your mind and can affect the problem) would be helpful for creating VM machine for testing.

**Comment by dazedcrazy** [comment] 2021-03-07 14:17
Both systems on the same Windows OS Build
![image](https://user-images.githubusercontent.com/9027988/110242826-aad28780-7f4f-11eb-9673-c838ce85eb8b.png)

**Comment by awawa-dev** [comment] 2021-03-07 15:27
Again, can not confirm it as I tested now on clean 20H2 version. Probable conflict with some other application that prevents & postpone installation of Microsoft VC++ libraries.

**Closed by awawa-dev** 2021-03-07 15:27 UTC
